build: false
shallow_clone: true
platform: x86
clone_folder: c:\projects\polyfill

cache:
    - c:\php -> appveyor.yml
    - vendor -> appveyor.yml

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1

install:
    - cinst wget
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - IF %PHP%==1 appveyor DownloadFile https://github.com/symfony/binary-utils/releases/download/v0.1/php-5.3.9-nts-Win32-VC9-x86.zip
    - IF %PHP%==1 7z x php-5.3.9-nts-Win32-VC9-x86.zip -y >nul
    - IF %PHP%==1 appveyor DownloadFile https://raw.githubusercontent.com/symfony/binary-utils/master/ICU-51.2-dlls.zip
    - IF %PHP%==1 7z x ICU-51.2-dlls.zip -y >nul
    - IF %PHP%==1 del /Q *.zip
    - IF %PHP%==1 cd ext
    - IF %PHP%==1 appveyor DownloadFile https://github.com/symfony/binary-utils/releases/download/v0.1/php_apcu-4.0.10-5.3-nts-vc9-x86.zip
    - IF %PHP%==1 7z x php_apcu-4.0.10-5.3-nts-vc9-x86.zip -y >nul
    - IF %PHP%==1 appveyor DownloadFile https://raw.githubusercontent.com/symfony/binary-utils/master/php_intl-3.0.0-5.3-nts-vc9-x86.zip
    - IF %PHP%==1 7z x php_intl-3.0.0-5.3-nts-vc9-x86.zip -y >nul
    - IF %PHP%==1 del /Q *.zip
    - IF %PHP%==1 cd ..
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - IF %PHP%==1 copy /Y php.ini-development php.ini
    - IF %PHP%==1 echo max_execution_time=1200 >> php.ini
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo memory_limit=-1 >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_apcu.dll >> php.ini
    - IF %PHP%==1 echo apc.enable_cli=1 >> php.ini
    - IF %PHP%==1 echo extension=php_intl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_ldap.dll >> php.ini
    - appveyor DownloadFile https://github.com/composer/composer/releases/download/1.9.0/composer.phar
    - cd c:\projects\polyfill
    - mkdir %APPDATA%\Composer && copy /Y .github\composer-config.json %APPDATA%\Composer\config.json
    - SET COMPOSER_ROOT_VERSION=dev-main
    - composer update --prefer-source --no-progress --ansi

test_script:
    - php -d allow_url_fopen=0 ./vendor/symfony/phpunit-bridge/bin/simple-phpunit
